apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: deployer
  name: deployer
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: deployer
          image: bcmehrman/deployer
          env:
            - name: DOCKER_IMAGE_PATH
              value: bcmehrman/simple-app:0.0.1
          command: ["bash", "run-app.sh"]
          resources:
            requests:
              memory: 200Mi
              cpu: 250m
            limits:
              memory: 4Gi
              cpu: 500m
      