
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind
  labels:
    component: docker
    app: dind
spec:
  selector:
    matchLabels:
      app: dind
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: dind
        component: docker
    spec:
      containers:
      - name: dind
        image: docker:dind
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        tty: true
        ports:
        - containerPort: 2375
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      restartPolicy: Always
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 30