FROM debian:10.10
ENV KUSTOMIZE_VER 4.1.3
ENV KUBECTL_VER 1.21.1

RUN apt-get update \
    && apt-get install -y curl bash gettext

RUN mkdir /working
WORKDIR /working

RUN curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
RUN mv kustomize /usr/local/bin/

RUN curl -L https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VER}/bin/linux/amd64/kubectl -o /usr/bin/kubectl \
    && chmod +x /usr/bin/kubectl

EXPOSE 8001
ENTRYPOINT ["/usr/bin/kubectl", "proxy"]
