apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - pv.yaml
 - pvc.yaml
 - rbac.yaml
 - deployment.yaml
 - service.yaml
 - secrets.yaml
configMapGenerator:
  - name: jcasc-config
    files:
      - jenkins.yaml 