apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize
  labels:
    app: kustomize
spec:
  selector:
    matchLabels:
      app: kustomize
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: kustomize
    spec:
      serviceAccountName: kustomize
      containers:
      - name: kustomize
        image: bcmehrman/kustomize:0.0.1
        imagePullPolicy: Always
        env:
        - name: FOO
          value: 'true'
        resources: 
          limits:
            memory: "256Mi"
            cpu: "500m"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
     