FROM bcmehrman/kustomize:0.0.1

# add scripts
ADD scripts/run-app.sh run-app.sh
ADD scripts/run-job.sh run-job.sh
# set to run on script by default
# https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.1.3/kustomize_v4.1.3_linux_amd64.tar.gz


ENTRYPOINT ["bash"]